#!/bin/bash
date >> /var/log/update_script.log ; echo '' >> /var/log/update_script.log ; echo 'updating sources:' >> /var/log/update_script.log ; apt-get update >> /var/log/update_script.log ; echo '' >> /var/log/update_script.log ; echo 'upgrading:' >> /var/log/update_script.log ; apt-get upgrade >> /var/log/update_script.log ; echo -e '\n' >> /var/log/update_script.log

# pour planifier une tache on ouvre la crontab via la commande crontab -e
# puis on insert la ligne suivante :
# 0 4  * * 6		root	date >> /var/log/update_script.log ; echo '' >> /var/log/update_script.log ; echo 'updating sources:' >> /var/log/update_script.log ; apt-get update >> /var/log/update_script.log ; echo '' >> /var/log/update_script.log ; echo 'upgrading:' >> /var/log/update_script.log ; apt-get upgrade >> /var/log/update_script.log ; echo -e '\n' >> /var/log/update_script.log
