#!/bin/bash
if	!( test -s ./sum )
then
	echo "Creating stock file."
	sleep 1
	md5sum /etc/crontab > sum
	echo "Done."
	exit
fi

echo "Creating compare file."
sleep 1
md5sum /etc/crontab > sum2

echo "Creating diff file which find difference between both file."
sleep 1
diff sum sum2 > diff

if	( test -s ./diff )
then
	echo "Modification detected on /etc/crontab"
	echo "Modification detected on /etc/crontab :" > mailfiles
	echo "" >> mailfiles
	cat diff >> mailfiles
	echo "send mail to root"
	cat mailfiles | mail -s "Crontab was modify" root
	rm mailfiles
	sleep 1
	echo "Updating stock file."
	sleep 1
	md5sum /etc/crontab > sum
else

	echo "No modification detected on /etc/crontab"

fi

echo "Deleting compare and diff files."
sleep 1
rm sum2
rm diff
echo "Done."
exit

# Pour planifier une tache on ouvre la crontab (/etc/crontab) ou crontab -e
# puis on insert la ligne suivante :
# 0 4 * * * ./pathdubinaire
